### ISSUE TITLE
How to upload mapping file

### ISSUE THREAD

**Issue by dt126** [GMatrixGames/TempMappingsRepo#1]
I'm sorry if it should be obvious, but I wanted to upload a usmap file and I cannot figure out how to do so. When trying to add to upload, I get an error that the file type is not supported. Thanks.

**Comment by GMatrixGames** [comment]
This is a repository for me to upload mappings used in the [Game Compatibility](https://github.com/FModel/Game-Compatibility) repository for FModel. If you have a game you would like to have validated, please open an issue on that repository for me to investigate it further.

**Comment by dt126** [comment]
Thank you. I was confused because some of the game reports on the FMODEL Discord had links to the Mappings on this github, so I assumed it was the person opening the game report that uploaded the mapping. I already opened on there and uploaded my mapping.
